/**
 * lang-zh.js - Simplified Chinese UI dictionary
 *
 * Keys are the English UI strings exactly as they appear in the DOM after
 * entity decoding, with runs of whitespace collapsed to one space. Anything
 * not listed here (parameter names, flight-mode names, units, telemetry
 * values, hardware model names) deliberately stays English.
 */

export const ZH = {
    // ── Chrome / tabs ──────────────────────────────────────────────────
    'FLIGHT DATA': '飞行数据',
    'FLIGHT PLAN': '飞行计划',
    'SETUP': '设置',
    'SYS CONFIG': '系统配置',
    'RELOADING MAP...': '正在重新加载地图...',
    'GROUND CONTROL STATION': '地面控制站',
    'LOADING...': '加载中...',
    'LANGUAGE': '语言',
    'English': 'English',
    '中文 (Chinese)': '中文 (Chinese)',

    // ── Flight screen ──────────────────────────────────────────────────
    'Airspeed': '空速',
    'Ground Spd': '地速',
    'G-Load': '过载',
    'Vert Speed': '垂直速度',
    'Altitude': '高度',
    'Terr Alt': '地形高度',
    'LiDAR': '激光测距',
    'Roll': '横滚',
    'Pitch': '俯仰',
    'Heading': '航向',
    'Battery V': '电池电压',
    'Battery A': '电池电流',
    'Battery %': '电量 %',
    'GPS Sats': 'GPS 卫星',
    'GPS HDOP': 'GPS HDOP',
    'Link Qual': '链路质量',
    'Vib X': '震动 X',
    'Vib Y': '震动 Y',
    'Vib Z': '震动 Z',
    'AoA': '迎角',
    'SSA': '侧滑角',
    'RTK Base': 'RTK 基线',
    'RTK Acc': 'RTK 精度',
    'DISARMED': '未解锁',
    'DEMO': '演示',
    'Rotor Load': '电机负载',
    'LATITUDE': '纬度',
    'LONGITUDE': '经度',
    'RADAR ALT': '雷达高度',
    'CALLSIGN': '呼号',
    'ALT (m)': '高度 (m)',
    'DIST (km)': '距离 (km)',

    // ── Annunciators ───────────────────────────────────────────────────
    'FAILSAFE': '失控保护',
    'LINK': '链路',
    'RC': '遥控',
    'GPS GLITCH': 'GPS 故障',
    'GPS JAM': 'GPS 干扰',
    'SPOOF': 'GPS 欺骗',
    'VIBE': '震动',
    'COMPASS': '罗盘',
    'BARO': '气压计',
    'AHRS': '姿态解算',
    'AIRSPD': '空速计',
    'MOTOR': '电机',
    'BATT': '电池',
    'FENCE': '围栏',
    '2D FIX': '2D 定位',
    'PREARM': '解锁检查',
    'MAG CAL': '罗盘校准',
    'IMU CAL': 'IMU 校准',
    'BARO CAL': '气压计校准',
    'BATT LOW': '电量低',
    'TERRAIN': '地形',
    'LOG': '日志',
    'LIDAR': '激光雷达',
    'OPT FLOW': '光流',
    'PROX': '近距感知',

    // ── Flight plan (route editor) ─────────────────────────────────────
    'Untitled route': '未命名航线',
    'Route settings': '航线设置',
    'Route menu': '航线菜单',
    'Route status': '航线状态',
    'LENGTH': '长度',
    'TIME': '时间',
    'WAYPOINTS': '航点',
    'MAX AGL': '最大离地高度',
    'UPLOAD': '上传',
    'SAVE': '保存',
    'LIBRARY': '任务库',
    'SEGMENTS': '航段',
    'ROUTE SETTINGS': '航线设置',
    'TAKE-OFF POINT': '起飞点',
    'AUTO': '自动',
    'Drag the H marker on the map to move it': '拖动地图上的 H 标记即可移动',
    'New route': '新建航线',
    'Invert direction': '反转方向',
    'Convert to waypoints': '转换为航点',
    'Zoom to route': '缩放至航线',
    'Import .waypoints…': '导入 .waypoints…',
    'Export .waypoints': '导出 .waypoints',
    'Clear route': '清空航线',
    'Satellite imagery': '卫星影像',
    'Show calculated waypoints': '显示计算航点',
    'SAT': '卫星',
    'FIT': '适应',
    'No segments yet': '尚无航段',
    'Select / pan (V)': '选择 / 平移 (V)',
    'Waypoint (W)': '航点 (W)',
    'Circle (C)': '盘旋 (C)',
    'Perimeter (P)': '周界 (P)',
    'Area scan (A)': '区域扫描 (A)',
    'Corridor (K)': '走廊 (K)',
    'Point of interest (I)': '兴趣点 (I)',
    'Landing (L)': '降落 (L)',
    'Waypoint': '航点',
    'Circle': '盘旋',
    'Perimeter': '周界',
    'Area scan': '区域扫描',
    'Corridor': '走廊',
    'Point of interest': '兴趣点',
    'Landing': '降落',
    'Speed': '速度',
    'Turn type': '转弯类型',
    'Hold': '悬停',
    'Accept radius': '到达半径',
    'Radius': '半径',
    'Loops': '圈数',
    'Direction': '方向',
    'Return to start': '返回起点',
    'Lane spacing': '航线间距',
    'Side distance': '侧向间距',
    'Camera FOV': '相机视场角',
    'Side overlap': '旁向重叠',
    'Forward overlap': '航向重叠',
    'Image width': '图像宽度',
    'Overshoot': '超出距离',
    'Double grid': '双网格',
    'Camera trigger by distance': '按距离触发相机',
    'Corridor width': '走廊宽度',
    'Camera': '相机',
    'Target height': '目标高度',
    'VTOL landing': '垂直降落',
    'Abort altitude': '中止高度',
    '+ add…': '+ 添加…',
    'Take a photo': '拍照',
    'Camera attitude': '相机姿态',
    'Set heading': '设置航向',
    'Wait': '等待',
    'Change speed': '改变速度',
    'Set servo': '设置舵机',
    'Set relay': '设置继电器',
    'Delete segment': '删除航段',
    'Remove action': '移除动作',
    'Altitude mode': '高度模式',
    'Default altitude': '默认高度',
    'AGL tolerance': '离地高度容差',
    'Default speed': '默认速度',
    'Automatic take-off': '自动起飞',
    'Take-off altitude': '起飞高度',
    'After last segment': '最后航段之后',
    'Max altitude AGL': '最大离地高度',
    'Min clearance': '最小净空',
    'Segment actions run': '航段动作执行',
    'Camera & gimbal': '相机与云台',
    'CAMERA & GIMBAL': '相机与云台',
    'GIMBAL': '云台',
    'Sensor width': '传感器宽度',
    'Sensor height': '传感器高度',
    'Focal length': '焦距',
    'Image height': '图像高度',
    'Default camera pitch': '默认相机俯仰',
    'Default camera yaw': '默认相机偏航',
    'Show camera footprints and POI view cones': '显示相机覆盖范围与兴趣点视锥',
    'CAM': '相机',
    'Path goes below the terrain': '航迹低于地形',
    'Pick a tool on the map and start drawing': '在地图上选择工具并开始绘制',
    'UPLOADING…': '上传中…',
    'READING…': '读取中…',
    'The route is empty': '航线为空',
    'SAVED': '已保存',
    'MISSION LIBRARY': '任务库',
    'SAVE AS NEW': '另存为新任务',
    'OPEN FOLDER': '打开文件夹',
    'SAVED MISSIONS': '已保存任务',
    'FLIGHT LOGS': '飞行日志',

    // ── Setup sidebar ──────────────────────────────────────────────────
    'COMMS': '通信',
    'CONNECTION': '连接',
    'Vehicle link · Serial / UDP / TCP': '飞行器链路 · 串口 / UDP / TCP',
    'TELEMETRY FORWARD': '数传转发',
    'MAVLink mirror · UDP / Serial / LTM': 'MAVLink 镜像 · UDP / 串口 / LTM',
    'RTK / GPS INJECT': 'RTK / GPS 注入',
    'NTRIP caster · Serial base': 'NTRIP 服务器 · 串口基站',
    'VEHICLE SETUP': '飞行器设置',
    'CALIBRATION': '校准',
    'Accel · Compass · Gyro': '加速度计 · 罗盘 · 陀螺仪',
    'RADIO CAL': '遥控器校准',
    'RC input range': '遥控输入范围',
    'JOYSTICK / RC': '摇杆 / 遥控',
    'Gamepad override': '手柄接管',
    'FLIGHT MODES': '飞行模式',
    'Mode switch mapping': '模式开关映射',
    'Battery · RC · GCS': '电池 · 遥控 · 地面站',
    'SERVO / RELAY': '舵机 / 继电器',
    'Output functions': '输出功能',
    'TUNING': '调参',
    'PID TUNING': 'PID 调参',
    'Rate & attitude gains': '角速度与姿态增益',
    'EXT TUNING': '扩展调参',
    'Extended tuning': '扩展调参',
    'VIBRATIONS': '震动',
    'IMU vibration & clipping': 'IMU 震动与削波',
    'PARAMETERS': '参数',
    'Full parameter list': '完整参数列表',
    'TOOLS': '工具',
    'SIMULATION': '仿真',
    'SITL launcher': 'SITL 启动器',
    'CORV SETUP': 'CORV 设置',
    'CORV binary config': 'CORV 二进制配置',

    // ── Connection ─────────────────────────────────────────────────────
    'CONNECTION TYPE': '连接类型',
    'MAVLink Serial': 'MAVLink 串口',
    'CORV Binary (Legacy)': 'CORV 二进制 (旧版)',
    'MSP Serial (INAV / Betaflight)': 'MSP 串口 (INAV / Betaflight)',
    'POLL RATE': '轮询速率',
    'Normal (USB / 115200)': '正常 (USB / 115200)',
    'Slow link (long-range radio)': '慢速链路 (远距离电台)',
    'SERIAL PORT': '串口',
    '-- Scan ports --': '-- 扫描端口 --',
    'SCAN': '扫描',
    'Scan': '扫描',
    'Scan ports': '扫描端口',
    'BAUD RATE': '波特率',
    'UDP HOST': 'UDP 主机',
    'UDP PORT': 'UDP 端口',
    'TCP HOST': 'TCP 主机',
    'TCP PORT': 'TCP 端口',
    'CONNECT': '连接',
    'DISCONNECT': '断开',
    'CONNECTING...': '连接中...',
    'CONNECTED': '已连接',
    'DISCONNECTED': '未连接',
    'Disconnected': '已断开',
    'FIRMWARE INFO': '固件信息',
    'AUTOPILOT': '飞控',
    'VEHICLE TYPE': '飞行器类型',
    'SYSTEM ID': '系统 ID',
    'MSP is request/response — the poll rate is the telemetry rate': 'MSP 为请求/应答模式 — 轮询速率即数传速率',
    'Simulator IP (e.g. 192.168.x.x)': '仿真器 IP (例如 192.168.x.x)',

    // ── Calibration ────────────────────────────────────────────────────
    'CALIBRATION WIZARD': '校准向导',
    'ACCELEROMETER': '加速度计',
    'Ready': '就绪',
    'GYROSCOPE': '陀螺仪',
    'Place vehicle level...': '将飞行器水平放置...',
    'Calibration complete!': '校准完成!',
    'Done': '完成',

    // ── Joystick ───────────────────────────────────────────────────────
    'JOYSTICK / GAMEPAD': '摇杆 / 手柄',
    'ENABLE RC OVERRIDE': '启用遥控接管',
    'GAMEPAD': '手柄',
    '-- No gamepad detected --': '-- 未检测到手柄 --',
    'SEND RATE': '发送速率',
    'STATUS': '状态',
    'Disabled': '已禁用',
    'Enabled': '已启用',
    'AXIS MAPPING': '轴映射',
    'Connect a gamepad and click SCAN': '连接手柄后点击“扫描”',
    'CHANNEL OUTPUT (PWM)': '通道输出 (PWM)',
    'RC INPUT CHANNELS': '遥控输入通道',
    'START CALIBRATION': '开始校准',
    'STOP CALIBRATION': '停止校准',
    'SAVE CALIBRATION': '保存校准',
    'RESET': '重置',
    'Move all sticks to extremes during calibration': '校准时请将所有摇杆推至极限',
    'Calibrating... move all sticks to extremes': '校准中... 请将所有摇杆推至极限',
    'Calibration stopped. Trim captured.': '校准已停止, 已记录中立位。',

    // ── Flight modes ───────────────────────────────────────────────────
    'MODE CHANNEL': '模式通道',
    'RC Channel 5': '遥控通道 5',
    'RC Channel 6': '遥控通道 6',
    'RC Channel 7': '遥控通道 7',
    'RC Channel 8': '遥控通道 8',
    'MODE 1': '模式 1',
    'MODE 2': '模式 2',
    'MODE 3': '模式 3',
    'MODE 4': '模式 4',
    'MODE 5': '模式 5',
    'MODE 6': '模式 6',
    'READ FROM VEHICLE': '从飞行器读取',
    'WRITE TO VEHICLE': '写入飞行器',

    // ── Failsafe ───────────────────────────────────────────────────────
    'BATTERY FAILSAFE': '电池失控保护',
    'LOW VOLTAGE': '低电压',
    'CRITICAL VOLTAGE': '严重低电压',
    'LOW ACTION': '低电量动作',
    'Land': '降落',
    'SmartRTL or RTL': '智能返航或返航',
    'SmartRTL or Land': '智能返航或降落',
    'Terminate': '终止',
    'CRITICAL ACTION': '严重低电量动作',
    'RC / GCS FAILSAFE': '遥控 / 地面站失控保护',
    'RC FAILSAFE': '遥控失控保护',
    'Enabled - Always RTL': '启用 - 始终返航',
    'Enabled - Continue Auto': '启用 - 继续自动任务',
    'Enabled - Always Land': '启用 - 始终降落',
    'RC PWM THRESHOLD': '遥控 PWM 阈值',
    'GCS FAILSAFE': '地面站失控保护',
    'READ FAILSAFE PARAMS': '读取失控保护参数',
    'WRITE FAILSAFE PARAMS': '写入失控保护参数',
    'WRITE ALL': '全部写入',

    // ── PID / tuning ───────────────────────────────────────────────────
    'RATE PID': '角速度 PID',
    'ROLL': '横滚',
    'PITCH': '俯仰',
    'YAW': '偏航',
    'ANGLE P': '角度 P',
    'ATTITUDE LIMITS': '姿态限制',
    'TECS — SPEED / HEIGHT': 'TECS — 速度 / 高度',
    'PRIMARY CONFIG': '主要配置',
    'EXTENDED TUNING': '扩展调参',
    'RATE ROLL/PITCH': '角速度 横滚/俯仰',
    'RATE YAW': '角速度 偏航',
    'LOITER SPEED (cm/s)': '悬停速度 (cm/s)',
    'WP SPEED (cm/s)': '航点速度 (cm/s)',
    'RTL ALT (cm)': '返航高度 (cm)',
    'PILOT SPEED UP (cm/s)': '手动上升速度 (cm/s)',
    'Read every value on this page from the vehicle': '从飞行器读取本页全部数值',
    'Write every value on this page to the vehicle': '将本页全部数值写入飞行器',

    // ── Parameters ─────────────────────────────────────────────────────
    'PARAM LIST': '参数列表',
    'All groups': '全部分组',
    'READ LISTED': '读取列表项',
    'READ ★': '读取 ★',
    'READ ALL': '全部读取',
    'WRITE CHANGED': '写入已修改',
    'SAVE .PARAM': '保存 .PARAM',
    'LOAD .PARAM': '加载 .PARAM',
    'NAME': '名称',
    'VALUE': '数值',
    'DESCRIPTION': '说明',
    'Type a parameter name...': '输入参数名称...',
    'Filter by parameter group': '按参数分组筛选',
    'Per-request timeout — raise it on high-latency links': '单次请求超时 — 高延迟链路请调高',
    'Read every parameter currently listed': '读取当前列出的全部参数',
    'Read all starred parameters': '读取全部星标参数',
    'Filter loaded parameters...': '筛选已加载参数...',

    // ── Vibrations ─────────────────────────────────────────────────────
    'VIBRATION LEVELS': '震动等级',
    'Clipping:': '削波:',
    'Threshold: <30 m/s² = good, 30-60 = marginal, >60 = high': '阈值: <30 m/s² = 良好, 30-60 = 一般, >60 = 过高',

    // ── Servo / relay ──────────────────────────────────────────────────
    'SERVO OUTPUT': '舵机输出',
    'RELAY CONTROL': '继电器控制',
    'RELAY 1': '继电器 1',
    'RELAY 2': '继电器 2',
    'RELAY 3': '继电器 3',
    'RELAY 4': '继电器 4',
    'OFF': '关',
    'ON': '开',
    'MANUAL SERVO TEST': '手动舵机测试',
    'SERVO #': '舵机 #',
    'SEND': '发送',

    // ── SITL ───────────────────────────────────────────────────────────
    'SITL LAUNCHER (ArduPilot)': 'SITL 启动器 (ArduPilot)',
    'Copter (Quad)': '多旋翼 (四轴)',
    'Copter 12S High-Speed': '多旋翼 12S 高速',
    'Tricopter 12S (3x X8 G2)': '三旋翼 12S (3x X8 G2)',
    'Helicopter': '直升机',
    'Plane': '固定翼',
    'QuadPlane': '垂起固定翼',
    'Rover': '车辆',
    'Sub': '潜航器',
    'VERSION': '版本',
    'Stable': '稳定版',
    'Beta': '测试版',
    'Latest (Dev)': '最新 (开发版)',
    'HOME POSITION': '返航点位置',
    'SPEED MULTIPLIER': '速度倍率',
    'LAUNCH & CONNECT': '启动并连接',
    'STARTING...': '启动中...',
    'STOP': '停止',
    'Not running': '未运行',
    'SITL stopped': 'SITL 已停止',
    'Connected to SITL': '已连接 SITL',
    'Binary not found, downloading...': '未找到程序, 正在下载...',
    'DOWNLOADING...': '下载中...',
    'DOWNLOADED': '已下载',
    'SITL MANUAL CONNECTION': 'SITL 手动连接',
    'HOST': '主机',
    'PORT': '端口',
    'CONNECT UDP': '连接 UDP',

    // ── RTK ────────────────────────────────────────────────────────────
    'CORRECTION SOURCE': '差分源',
    'SOURCE': '来源',
    'NTRIP Caster (Internet)': 'NTRIP 服务器 (互联网)',
    'Serial Base Station': '串口基站',
    'Not connected': '未连接',
    'Connecting to caster...': '正在连接服务器...',
    'NTRIP CASTER': 'NTRIP 服务器',
    'MOUNTPOINT': '挂载点',
    'LIST': '列表',
    'SOURCETABLE': '源列表',
    'Fetch caster sourcetable': '获取服务器源列表',
    'USERNAME': '用户名',
    'PASSWORD': '密码',
    'USE TLS': '使用 TLS',
    'GGA UPLOAD (VRS)': 'GGA 上传 (VRS)',
    'Off': '关',
    'Vehicle position': '飞行器位置',
    'Manual position': '手动位置',
    'LAT': '纬度',
    'LON': '经度',
    'Lat': '纬度',
    'Lon': '经度',
    'ALT (M)': '高度 (M)',
    'GGA INTERVAL (S)': 'GGA 间隔 (S)',
    'SERIAL BASE STATION': '串口基站',
    'Select port...': '选择端口...',
    'RTK STREAM STATUS': 'RTK 数据流状态',
    'No data': '无数据',
    'MSG RATE': '消息速率',
    'TOTAL MSGS': '消息总数',
    'BYTES RX': '接收字节',
    'GGA SENT': '已发送 GGA',
    'RECONNECTS': '重连次数',
    'RTCM MESSAGE TYPES': 'RTCM 消息类型',
    'No messages yet': '暂无消息',
    'DRONE RTK STATUS': '飞行器 RTK 状态',
    'GPS FIX': 'GPS 定位',
    'SATELLITES': '卫星数',
    'BASELINE': '基线',
    'ACCURACY': '精度',
    'IAR HYPOTHESES': 'IAR 假设数',

    // ── Telemetry forward ──────────────────────────────────────────────
    'ADD OUTPUT': '添加输出',
    'OUTPUT TYPE': '输出类型',
    'UDP Client (send to host)': 'UDP 客户端 (发送至主机)',
    'UDP Server (listen)': 'UDP 服务端 (监听)',
    'Serial Port': '串口',
    'LISTEN PORT': '监听端口',
    'PROTOCOL': '协议',
    'MAVLink Passthrough': 'MAVLink 透传',
    'LTM (Lightweight Telemetry)': 'LTM (轻量级数传)',
    'WRITE ACCESS (BIDIRECTIONAL)': '写入权限 (双向)',
    'Packets received from this endpoint are injected into the vehicle link (a secondary GCS can send commands)': '从该端点收到的数据包将注入飞行器链路 (副地面站可发送命令)',
    'ACTIVE OUTPUTS': '活动输出',
    'No outputs configured': '未配置输出',
    'Output started': '输出已启动',
    'Select a serial port first': '请先选择串口',
    'Enter UDP host and port': '请输入 UDP 主机和端口',
    'Enter a listen port': '请输入监听端口',
    'REMOVE': '移除',
    'CURRENT DATA': '当前数据',
    'HEADING': '航向',
    'GROUNDSPEED': '地速',

    // ── CORV setup ─────────────────────────────────────────────────────
    'GPS TYPE': 'GPS 类型',
    'GPS BAUD RATE': 'GPS 波特率',
    'TELEMETRY OUTPUT': '数传输出',
    'SERIAL1 PROTOCOL': 'SERIAL1 协议',
    'Binary Custom': '自定义二进制',
    'SERIAL1 BAUD': 'SERIAL1 波特率',
    'USB TELEMETRY': 'USB 数传',
    'SERIAL1 TELEMETRY': 'SERIAL1 数传',
    'NAV RATE (Hz)': '导航速率 (Hz)',
    'DEBUG RATE (Hz)': '调试速率 (Hz)',
    'RAW RATE (Hz)': '原始数据速率 (Hz)',
    'FEATURE FLAGS': '功能开关',
    'MAGNETOMETER': '磁力计',
    'MAG BUS': '磁力计总线',
    'SPI (onboard RM3100)': 'SPI (板载 RM3100)',
    'EARTH ROTATION COMP': '地球自转补偿',
    'ZUPT': '零速修正 (ZUPT)',
    'ACCEL LEVELING': '加速度计调平',
    'WIND ESTIMATION': '风速估计',
    'AIRSPEED': '空速',
    'AIRSPEED BUS': '空速计总线',
    'PITOT MOUNT AXIS': '皮托管安装轴',
    'X — Front (fixed-wing)': 'X — 前向 (固定翼)',
    'Z — Up (multirotor)': 'Z — 上向 (多旋翼)',
    'AIRSPEED RATIO': '空速比',
    'SIDESLIP σ VALID FLIGHT (deg)': '侧滑 σ 有效飞行 (deg)',
    'AoA VALID RANGE ± (deg)': '迎角有效范围 ± (deg)',
    'AIRSPEED ANGLE LEGACY (deg)': '空速角 (旧版) (deg)',
    'BOARD & HARDWARE': '板卡与硬件',
    'BOARD TYPE': '板卡类型',
    'FULL — Dual IMU, Mag': '完整版 — 双 IMU, 磁力计',
    'MINI — Single IMU, No Mag': '精简版 — 单 IMU, 无磁力计',
    'GPS NOISE SIM': 'GPS 噪声仿真',
    'PARTICLE FILTER': '粒子滤波',
    'N PARTICLES (32-256)': '粒子数 (32-256)',
    'ESS THRESHOLD (0.1-0.7)': 'ESS 阈值 (0.1-0.7)',
    'ROUGHENING RP (rad)': '粗化 RP (rad)',
    'ROUGHENING POS (m)': '粗化位置 (m)',
    'ROUGHENING VEL (m/s)': '粗化速度 (m/s)',
    'GPS SIGMA H LEGACY': 'GPS 水平 σ (旧版)',
    'GPS SIGMA V LEGACY': 'GPS 垂直 σ (旧版)',
    'SHARED EKF BIAS NOISE (Q diagonal)': '共享 EKF 偏置噪声 (Q 对角)',
    'GYRO BIAS ((rad/s)²/s)': '陀螺偏置 ((rad/s)²/s)',
    'ACCEL BIAS ((m/s²)²/s)': '加速度计偏置 ((m/s²)²/s)',
    'HARD IRON (nT²/s)': '硬铁 (nT²/s)',
    'BARO BIAS (m²/s)': '气压计偏置 (m²/s)',
    'WIND ((m/s)²/s)': '风 ((m/s)²/s)',
    'SHARED EKF INITIAL COVARIANCE': '共享 EKF 初始协方差',
    'GYRO BIAS (rad²/s²)': '陀螺偏置 (rad²/s²)',
    'ACCEL BIAS (m²/s⁴)': '加速度计偏置 (m²/s⁴)',
    'HARD IRON (nT²)': '硬铁 (nT²)',
    'BARO BIAS (m²)': '气压计偏置 (m²)',
    'WIND (m²/s²)': '风 (m²/s²)',
    'PER-PARTICLE EKF PROCESS NOISE': '单粒子 EKF 过程噪声',
    'ACCEL PSD Q ((m/s²)²/Hz)': '加速度 PSD Q ((m/s²)²/Hz)',
    'POSITION RW Q (m²/s)': '位置随机游走 Q (m²/s)',
    'ACTIONS': '操作',
    'Connect via CORV Binary and click READ to load device configuration': '通过 CORV 二进制连接后点击“读取”以加载设备配置',
    'READ': '读取',
    'WRITE + SAVE': '写入并保存',

    // ── System config ──────────────────────────────────────────────────
    'SYSTEM CONFIG': '系统配置',
    'ALTITUDE OFFSET (M)': '高度偏移 (M)',
    'TERRAIN (HGT FOLDER)': '地形 (HGT 文件夹)',
    'SELECT HGT FOLDER': '选择 HGT 文件夹',
    'NO DATA': '无数据',
    '3D MODEL': '3D 模型',
    'Loading...': '加载中...',
    'MODEL SCALE:': '模型缩放:',
    'TIME OF DAY (DEBUG):': '时刻 (调试):',
    'MAP BRIGHTNESS (STATIC):': '地图亮度 (静态):',
    'ATTITUDE SMOOTHING:': '姿态平滑:',
    'DEVTOOLS': '开发者工具',
    'OPEN DEVTOOLS': '打开开发者工具',
    'GCS OPTIONS': '地面站选项',
    'ADS-B TRAFFIC': 'ADS-B 交通',
    'Show ADS-B traffic overlay': '显示 ADS-B 交通叠加层',
    'GROUND CLAMP': '贴地',
    'Clamp model to terrain surface': '将模型贴合地形表面',
    'BATTERY MIN VOLTAGE': '电池最低电压',
    'BATTERY MAX VOLTAGE': '电池最高电压',
    'CELLS (AUTO)': '电芯数 (自动)',
    'ROTOR LOAD': '电机负载',
    'SCHEMATIC': '示意图',
    'Show rotor load schematic': '显示电机负载示意图',
    'FRAME': '机架',
    'AUTO (from MAV_TYPE)': '自动 (根据 MAV_TYPE)',
    'SINGLE ROTOR (plane / heli)': '单旋翼 (固定翼 / 直升机)',
    'TRICOPTER (3)': '三旋翼 (3)',
    'QUAD (4)': '四旋翼 (4)',
    'HEXA (6)': '六旋翼 (6)',
    'OCTO (8)': '八旋翼 (8)',
    'DECA (10)': '十旋翼 (10)',
    'DODECA (12)': '十二旋翼 (12)',
    'MOTORS OFF PWM (SCALE MIN)': '电机停止 PWM (刻度最小)',
    'SCALE MAX PWM': '刻度最大 PWM',
    'GREEN ABOVE PWM': '绿色阈值 PWM',
    'ORANGE ABOVE PWM': '橙色阈值 PWM',
    'RED ABOVE PWM': '红色阈值 PWM',
    'SINGLE ROTOR CHANNEL': '单旋翼通道',
    'Below the green threshold the gauges read blue (motors stopped). Plane and helicopter show only the main rotor, on the channel above (ArduPlane throttle = 3, heli RSC = 8).':
        '低于绿色阈值时仪表显示蓝色 (电机停止)。固定翼和直升机仅显示主旋翼, 通道见上方 (ArduPlane 油门 = 3, 直升机 RSC = 8)。',
    'SIYI CAMERA STREAM': 'SIYI 相机视频流',
    'IP ADDRESS': 'IP 地址',
    'RTSP PORT': 'RTSP 端口',
    'STREAM PATH': '流路径',
    'TARGET FPS': '目标帧率',
    'Network adapter: static IP in the 192.168.144.x subnet. ffmpeg must be in PATH.': '网络适配器: 静态 IP 须在 192.168.144.x 网段。ffmpeg 须在 PATH 中。',
    // ── LiDAR (Livox Mid-360) ──────────────────────────────────────────
    'LIDAR · LIVOX MID-360': '激光雷达 · LIVOX MID-360',
    'POINT CLOUD': '点云',
    'Connect to the LiDAR and draw the 3D map': '连接激光雷达并绘制 3D 地图',
    'LIDAR IP': '雷达 IP',
    'HOST IP (POINT DESTINATION)': '主机 IP (点云目的地)',
    'AUTO (interface on the LiDAR subnet)': '自动 (雷达所在网段的网卡)',
    'POINT FORMAT': '点格式',
    'MOUNT ATTITUDE VS IMU (ROLL / PITCH / YAW °)': '相对 IMU 的安装姿态 (横滚 / 俯仰 / 偏航 °)',
    'Preset…': '预设…',
    'Upright, connector aft (Z up)': '正装, 接口朝后 (Z 向上)',
    'Inverted under the belly (Z down)': '机腹倒装 (Z 向下)',
    'Inverted, rotated 90°': '倒装, 旋转 90°',
    'Upright, nose-down 45°': '正装, 前倾 45°',
    'Forward-looking (Z fwd)': '前视 (Z 向前)',
    'LEVER ARM IMU → LIDAR (X FWD / Y RIGHT / Z DOWN, m)': 'IMU → 雷达 杆臂 (X 前 / Y 右 / Z 下, m)',
    'TELEMETRY LAG (ms)': '遥测延迟 (ms)',
    'MIN RANGE — DISCARD CLOSER THAN (m)': '最小量程 — 丢弃近于 (m)',
    'rudder, landing gear, antennas in the field of view': '视场内的方向舵、起落架、天线',
    'MAX RANGE (m)': '最大量程 (m)',
    'VOXEL SIZE (m) / MAX POINTS': '体素尺寸 (m) / 最大点数',
    'NOISE FILTER': '噪点过滤',
    'Drop points the LiDAR tags as noise': '丢弃雷达标记为噪点的点',
    'ACCUMULATE ONLY WITH': '仅在以下条件累积',
    'GPS 3D fix or better': 'GPS 3D 定位或更好',
    'DGPS or better': 'DGPS 或更好',
    'RTK float or better': 'RTK 浮点或更好',
    'RTK fixed': 'RTK 固定',
    'EKF healthy (position flags + variances)': 'EKF 正常 (位置标志 + 方差)',
    'COLOR BY / POINT SIZE (px)': '着色方式 / 点大小 (px)',
    'Height': '高度',
    'Reflectivity': '反射率',
    'Draw through the terrain mesh (SRTM is coarser than the LiDAR)': '穿透地形网格绘制 (SRTM 精度低于激光雷达)',
    'RECORD RAW POINTS (.PLY)': '记录原始点 (.PLY)',
    'Stream every point to data/lidar/raw-*.ply': '将每个点写入 data/lidar/raw-*.ply',
    'CLEAR MAP': '清除地图',
    'SAVE MAP .PLY': '保存地图 .PLY',
    'Livox SDK2 over UDP: the LiDAR must reach this host on ports 56101 / 56201 / 56301 / 56401 through the LAN bridge. Raise SR_POSITION and SR_EXTRA1 to 10 Hz for a sharper map.':
        'Livox SDK2 UDP 协议: 雷达须能通过网桥访问本机的 56101 / 56201 / 56301 / 56401 端口。将 SR_POSITION 与 SR_EXTRA1 提高到 10 Hz 可获得更清晰的地图。',
    'LIVE POINTS (NOT GEOREFERENCED) FADE AFTER (s)': '实时点 (未地理配准) 淡出时间 (s)',
    'MOUNT & FILTERS': '安装与过滤',
    'Livox Mid-360 · point cloud': 'Livox Mid-360 · 点云',
    'Angles are ZYX Euler of the LiDAR body relative to the aircraft body (FRD). The Mid-360 sees 360° × (-7°…+52°): mounted flat under the belly it is blind straight down, tilt it to close the gap.':
        '角度为雷达本体相对机体 (FRD) 的 ZYX 欧拉角。Mid-360 视场为 360° × (-7°…+52°): 平装于机腹时正下方为盲区, 倾斜安装可消除。',
    'ACCUMULATING': '累积中',
    'SEARCHING': '搜索中',
    'MAP FULL': '地图已满',
    'OFFLINE DATA DOWNLOAD': '离线数据下载',
    'NORTH LAT': '北界纬度',
    'SOUTH LAT': '南界纬度',
    'WEST LON': '西界经度',
    'EAST LON': '东界经度',
    'SATELLITE ZOOM MAX': '卫星最大缩放级别',
    'Satellite tiles': '卫星瓦片',
    'SRTM1 elevation': 'SRTM1 高程',
    'CANCEL': '取消',
    'OK': '确定',
    'HUD DATA FIELDS': 'HUD 数据字段',
    'LEFT 1': '左 1',
    'LEFT 2': '左 2',
    'LEFT 3': '左 3',
    'RIGHT 1': '右 1',
    'RIGHT 2': '右 2',
    'RIGHT 3': '右 3',
    'RESET DEFAULTS': '恢复默认',
    'MAVLINK STREAM RATES (Hz)': 'MAVLink 数据流速率 (Hz)',
    'RAW SENSORS': '原始传感器',
    'EXT STATUS': '扩展状态',
    'RC CHANNELS': '遥控通道',
    'RAW CTRL': '原始控制',
    'POSITION': '位置',
    'EXTRA1 (ATTITUDE)': 'EXTRA1 (姿态)',
    'PARAMS': '参数',
    'READ STREAM RATES': '读取数据流速率',
    'WRITE STREAM RATES': '写入数据流速率',
    'RAW DATA STREAM': '原始数据流',
    'IAS': '指示空速',
    'GS': '地速',
    'VS': '垂直速度',
    'ACC X': '加速度 X',
    'ACC Y': '加速度 Y',
    'ACC Z': '加速度 Z',

    // ── Command bar / GCS sidebar ──────────────────────────────────────
    'No Fix': '无定位',
    'No GPS': '无 GPS',
    '2D Fix': '2D 定位',
    '3D Fix': '3D 定位',
    'RTK Float': 'RTK 浮点',
    'RTK Fixed': 'RTK 固定',
    'ARM': '解锁',
    'DISARM': '上锁',
    'ARMED': '已解锁',
    'TAKEOFF': '起飞',
    'SPD': '速度',
    'SET': '设定',
    'Home': '返航点',
    'WP': '航点',
    'Heartbeat': '心跳',
    'Flight mode': '飞行模式',
    'Pre-arm status': '解锁前检查状态',
    'ARM / DISARM': '解锁 / 上锁',
    'Takeoff': '起飞',
    'Return to Launch': '返航',
    'Start AUTO mission': '开始自动任务',
    'Fly By Wire A': '线传 A (FBWA)',
    'Position Hold': '定点悬停',
    'Emergency Land': '紧急降落',
    'Mission speed (m/s)': '任务速度 (m/s)',
    'Send speed command': '发送速度命令',
    'Straight-line distance to home': '到返航点的直线距离',
    'Active waypoint / mission length': '当前航点 / 任务航点数',
    'Toggle GCS Controls': '切换地面站控制面板',
    'VEHICLE': '飞行器',
    'TYPE': '类型',
    'SYS ID': '系统 ID',
    'FW': '固件',
    'REBOOT FC': '重启飞控',
    'MISSION': '任务',
    'READ MISSION': '读取任务',
    'WPT:': '航点:',
    'MUTE GCS OUTPUT': '静默地面站输出',
    'SHOW ADS-B TRAFFIC': '显示 ADS-B 交通',
    'SHOW ROTOR LOAD': '显示电机负载',
    'CLEAR TRAIL': '清除轨迹',
    'RTL OPTIONS': '返航选项',
    'RTL ALT (m)': '返航高度 (m)',
    'RTL ALT FINAL (m)': '返航最终高度 (m)',
    'RTL SPEED (m/s)': '返航速度 (m/s)',
    'SMART RTL': '智能返航',
    'SRTL POINTS': '智能返航点数',
    'SRTL ACCURACY (m)': '智能返航精度 (m)',
    'TARGET': '目标',
    'SET TARGET': '设置目标',
    'CLEAR': '清除',
    'MESSAGE LOG': '消息日志',
    'No messages yet...': '暂无消息...',

    // ── Loading / FPV / misc controller strings ────────────────────────
    'SYSTEMS READY': '系统就绪',
    'LOADING TERRAIN DATA...': '正在加载地形数据...',
    'FPV Camera — click to start stream': 'FPV 相机 — 点击开始视频流',
    'FPV Camera active — click for AR overlay': 'FPV 相机已开启 — 点击切换 AR 叠加',
    'AR Mode active — click to stop': 'AR 模式已开启 — 点击停止',
    'AR overlay active': 'AR 叠加已开启',
    'Connecting to camera...': '正在连接相机...',
    'FPV not available': 'FPV 不可用',
    'Stream connected': '视频流已连接',
    'Stream disconnected': '视频流已断开',
    'Stream stopped': '视频流已停止',
    'HOME set to current position.': '返航点已设为当前位置。',
    'No waypoints to save.': '没有可保存的航点。',
    'LOADED': '已加载',
    'PAUSED': '已暂停',
    'PLAYING': '播放中',
    'UNLOADED': '已卸载',
    'ACTIVE': '活动',
    'CONNECTING': '连接中',
    'Pause': '暂停',

    // ── Arm / disarm ───────────────────────────────────────────────────
    'FORCE ARM': '强制解锁',
    'FORCE DISARM': '强制上锁',
    'DISARM the vehicle (currently ARMED)': '给飞行器上锁 (当前已解锁)',
    'ARM the vehicle (currently DISARMED)': '给飞行器解锁 (当前未解锁)',
    'Pre-arm: OK': '解锁前检查: 通过',
    'Pre-arm: Check failed': '解锁前检查: 未通过',
    'Pre-arm: Unknown': '解锁前检查: 未知',
    'DISARM the vehicle?': '给飞行器上锁?',
    'ARM the vehicle?': '给飞行器解锁?',
    'Sends MAV_CMD_COMPONENT_ARM_DISARM (400) with param1=0. The autopilot refuses a normal disarm while the vehicle is flying or not landed.':
        '发送 MAV_CMD_COMPONENT_ARM_DISARM (400), param1=0。飞行器在飞行中或未着陆时, 飞控会拒绝普通上锁。',
    ' The vehicle currently looks airborne — a normal disarm will most likely be rejected.':
        ' 飞行器当前似乎在空中 — 普通上锁很可能被拒绝。',
    'FORCE DISARM sends param2=21196: it bypasses the disarm checks and cuts the motors immediately, in flight too. The vehicle will fall.':
        '强制上锁发送 param2=21196: 跳过上锁检查并立即切断电机, 飞行中同样如此。飞行器将会坠落。',
    'Ensure the area is clear. Sends MAV_CMD_COMPONENT_ARM_DISARM (400) with param1=1. The autopilot runs all pre-arm checks (GPS, EKF, compass, battery, safety switch) and refuses if any fails.':
        '请确认周围无人。发送 MAV_CMD_COMPONENT_ARM_DISARM (400), param1=1。飞控会执行全部解锁前检查 (GPS, EKF, 罗盘, 电池, 安全开关), 任一失败即拒绝。',
    ' Pre-arm checks are currently NOT passing.': ' 解锁前检查当前未通过。',
    'FORCE ARM sends param2=21196: it skips every pre-arm check. The props can spin with a bad EKF, no GPS fix or a failing sensor. Use only if you know exactly which check is failing and why.':
        '强制解锁发送 param2=21196: 跳过所有解锁前检查。EKF 异常、无 GPS 定位或传感器故障时螺旋桨仍会转动。仅在明确知道哪项检查失败及原因时使用。',

    // ── Status lines / hints ───────────────────────────────────────────
    'No waypoints generated — try smaller spacing': '未生成航点 — 请尝试更小的间距',
    'Draw a survey area first using the survey tool on the map toolbar': '请先用地图工具栏中的测绘工具绘制测绘区域',
    'Clear survey': '清除测绘',
    'Clear mission': '清除任务',
    'Edit parameter': '编辑参数',
    'Change command': '修改命令',
    'Change altitude': '修改高度',
    'Nothing to undo': '没有可撤销的操作',
    'Nothing to redo': '没有可重做的操作',
    'No vehicle position available': '没有可用的飞行器位置',
    'No waypoints to upload': '没有可上传的航点',
    'Running...': '运行中...',
    'Failed': '失败',
    'Error': '错误',
    'No Gamepad': '无手柄',
    'Enter the caster host first': '请先输入服务器主机',
    'Caster returned an empty sourcetable': '服务器返回了空的源列表',
    'Caster host and mountpoint are required': '需要服务器主机和挂载点',
    'Stop calibration first': '请先停止校准',
    'Another calibration is in progress': '另一项校准正在进行中',
    'Config loaded from device': '已从设备加载配置',
    'Write access: packets from this endpoint are injected into the vehicle link': '写入权限: 来自该端点的数据包将注入飞行器链路',

    // ── Log replay ─────────────────────────────────────────────────────
    'LOG REPLAY': '日志回放',
    'OPEN LOG FILE...': '打开日志文件...',
    'FILE': '文件',
    'FORMAT': '格式',
    'DUR': '时长',
    'MSGS': '消息数',
    'UNLOAD': '卸载',
    'Unload log': '卸载日志',
    'Load an ArduPilot': '加载 ArduPilot',
    'or': '或',
    'to replay a past flight.': '以回放历史飞行。',
    'REPLAY': '回放',
    'Play': '播放',
    'Close': '关闭',

    // ── Header tooltips ────────────────────────────────────────────────
    'FPV Camera (enable/disable stream)': 'FPV 相机 (启用/禁用视频流)',
    'FPV Camera': 'FPV 相机',
    'Satellite overlay (M)': '卫星图层 (M)',
    'Toggle realistic sunlight (L)': '切换真实光照 (L)',
    'Toggle 1st/3rd person camera': '切换第一/第三人称视角',
    'Horizon-lock view — pitch always level (T)': '地平线锁定视图 — 俯仰始终水平 (T)',
    'Predicted trajectory corridor (P)': '预测航迹走廊 (P)',
    'Toggle light/dark theme': '切换明暗主题',
    'Deselect': '取消选择',
    'Currently loaded mission': '当前加载的任务',
    'Undo (Ctrl+Z)': '撤销 (Ctrl+Z)',
    'Redo (Ctrl+Y)': '重做 (Ctrl+Y)',
    'Save to the local mission library': '保存到本地任务库',
    'Open the local mission library': '打开本地任务库',
    'Save the current plan as a new mission': '将当前计划另存为新任务',
    'Open the data folder': '打开数据文件夹',
};
