/**
 * TextureCompressWorker.js - RGBA → BC1 (DXT1) compression for terrain textures
 *
 * Terrain satellite textures used to be uploaded as RGBA8 CanvasTextures: 4 bytes
 * per pixel plus a mip chain, so a single 4096² chunk texture cost ~90 MB of VRAM.
 * BC1 stores a 4×4 block in 8 bytes — half a byte per pixel, 8× less — and the GPU
 * samples it natively, so it also cuts texture bandwidth, which is what actually
 * bounds the frame on a terrain view.
 *
 * The worker returns a full mip chain because compressed textures cannot be
 * mip-generated by the driver: without it, distant terrain aliases badly.
 *
 * Two details that are easy to get wrong and are handled here:
 *   - BC1 requires dimensions that are multiples of 4. The image is padded by
 *     replicating its edge pixels; the caller maps UVs onto the unpadded region
 *     with texture.repeat, so no ground offset is introduced.
 *   - THREE.CompressedTexture ignores flipY. Level 0 is therefore flipped
 *     vertically here, and the padding ends up on the top/right after the flip —
 *     which is why repeat alone (with no offset) is the correct UV correction.
 */

/** Box-filter halving of an RGBA image. Odd sizes clamp to the last row/column. */
function downsample(src, w, h) {
    const dw = Math.max(1, w >> 1);
    const dh = Math.max(1, h >> 1);
    const dst = new Uint8Array(dw * dh * 4);
    for (let y = 0; y < dh; y++) {
        const sy0 = y * 2;
        const sy1 = Math.min(sy0 + 1, h - 1);
        for (let x = 0; x < dw; x++) {
            const sx0 = x * 2;
            const sx1 = Math.min(sx0 + 1, w - 1);
            const i00 = (sy0 * w + sx0) * 4, i01 = (sy0 * w + sx1) * 4;
            const i10 = (sy1 * w + sx0) * 4, i11 = (sy1 * w + sx1) * 4;
            const o = (y * dw + x) * 4;
            for (let c = 0; c < 4; c++) {
                dst[o + c] = (src[i00 + c] + src[i01 + c] + src[i10 + c] + src[i11 + c] + 2) >> 2;
            }
        }
    }
    return { data: dst, width: dw, height: dh };
}

/** Pad to a multiple of 4 by replicating the last row/column. */
function padTo4(src, w, h) {
    const pw = (w + 3) & ~3;
    const ph = (h + 3) & ~3;
    if (pw === w && ph === h) return { data: src, width: w, height: h };
    const dst = new Uint8Array(pw * ph * 4);
    for (let y = 0; y < ph; y++) {
        const sy = Math.min(y, h - 1);
        for (let x = 0; x < pw; x++) {
            const sx = Math.min(x, w - 1);
            const s = (sy * w + sx) * 4;
            const d = (y * pw + x) * 4;
            dst[d] = src[s]; dst[d + 1] = src[s + 1];
            dst[d + 2] = src[s + 2]; dst[d + 3] = src[s + 3];
        }
    }
    return { data: dst, width: pw, height: ph };
}

/** Flip an RGBA image vertically, in place-ish (returns a new buffer). */
function flipY(src, w, h) {
    const dst = new Uint8Array(src.length);
    const stride = w * 4;
    for (let y = 0; y < h; y++) {
        const s = y * stride;
        const d = (h - 1 - y) * stride;
        dst.set(src.subarray(s, s + stride), d);
    }
    return dst;
}

function to565(r, g, b) {
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

/** Expand a 565 endpoint back to 8-bit, the way the GPU does, for index selection. */
function from565(c, out) {
    const r = (c >> 11) & 0x1f, g = (c >> 5) & 0x3f, b = c & 0x1f;
    out[0] = (r << 3) | (r >> 2);
    out[1] = (g << 2) | (g >> 4);
    out[2] = (b << 3) | (b >> 2);
}

const blockPx = new Uint8Array(16 * 3);
const c0e = new Uint8Array(3), c1e = new Uint8Array(3);
const palette = new Uint8Array(4 * 3);

/**
 * Encode one 4×4 block into 8 bytes of BC1.
 * Endpoints come from the bounding box of the block, inset by 1/16 of its extent —
 * the standard cheap approximation of a principal-axis fit. It is a fraction of a dB
 * worse than a full PCA fit and several times faster, which matters because a near
 * chunk is 16 M pixels.
 */
function encodeBlock(src, w, bx, by, out, outOff) {
    let minR = 255, minG = 255, minB = 255;
    let maxR = 0, maxG = 0, maxB = 0;

    for (let y = 0; y < 4; y++) {
        const row = (by + y) * w;
        for (let x = 0; x < 4; x++) {
            const s = (row + bx + x) * 4;
            const r = src[s], g = src[s + 1], b = src[s + 2];
            const p = (y * 4 + x) * 3;
            blockPx[p] = r; blockPx[p + 1] = g; blockPx[p + 2] = b;
            if (r < minR) minR = r; if (r > maxR) maxR = r;
            if (g < minG) minG = g; if (g > maxG) maxG = g;
            if (b < minB) minB = b; if (b > maxB) maxB = b;
        }
    }

    // Inset the bounding box: the extremes are usually outliers, and pulling the
    // endpoints in reduces the error of the two interpolated colours.
    const insetR = (maxR - minR) >> 4, insetG = (maxG - minG) >> 4, insetB = (maxB - minB) >> 4;
    minR = Math.min(255, minR + insetR); maxR = Math.max(0, maxR - insetR);
    minG = Math.min(255, minG + insetG); maxG = Math.max(0, maxG - insetG);
    minB = Math.min(255, minB + insetB); maxB = Math.max(0, maxB - insetB);

    let c0 = to565(maxR, maxG, maxB);
    let c1 = to565(minR, minG, minB);

    // c0 > c1 selects the 4-colour (opaque) mode. Equal endpoints mean a flat
    // block: any index works, so emit the cheapest encoding.
    if (c0 === c1) {
        out[outOff] = c0 & 0xff; out[outOff + 1] = (c0 >> 8) & 0xff;
        out[outOff + 2] = c1 & 0xff; out[outOff + 3] = (c1 >> 8) & 0xff;
        out[outOff + 4] = 0; out[outOff + 5] = 0; out[outOff + 6] = 0; out[outOff + 7] = 0;
        return;
    }
    let swapped = false;
    if (c0 < c1) { const t = c0; c0 = c1; c1 = t; swapped = true; }

    from565(c0, c0e);
    from565(c1, c1e);
    palette[0] = c0e[0]; palette[1] = c0e[1]; palette[2] = c0e[2];
    palette[3] = c1e[0]; palette[4] = c1e[1]; palette[5] = c1e[2];
    for (let c = 0; c < 3; c++) {
        palette[6 + c] = (2 * c0e[c] + c1e[c] + 1) / 3 | 0;
        palette[9 + c] = (c0e[c] + 2 * c1e[c] + 1) / 3 | 0;
    }
    // Endpoint order was swapped, so the palette order the GPU will build is the
    // one above — nothing else to correct, the index search uses this palette.
    void swapped;

    // Index selection by projection onto the endpoint axis rather than four
    // distance tests per pixel. The four palette entries lie at t = 0, 1/3, 2/3, 1
    // along c1→c0, so a single dot product plus three comparisons picks the nearest
    // one. Roughly 3× the throughput of the exhaustive search for ~0.3 dB, which
    // matters: a near chunk is 16 M pixels.
    const dr0 = c0e[0] - c1e[0], dg0 = c0e[1] - c1e[1], db0 = c0e[2] - c1e[2];
    const lenSq = dr0 * dr0 + dg0 * dg0 + db0 * db0;
    const inv = lenSq > 0 ? 1 / lenSq : 0;

    let indices = 0;
    for (let i = 15; i >= 0; i--) {
        const p = i * 3;
        const t = ((blockPx[p] - c1e[0]) * dr0 +
                   (blockPx[p + 1] - c1e[1]) * dg0 +
                   (blockPx[p + 2] - c1e[2]) * db0) * inv;
        // t≈0 → c1 (index 1), t≈1 → c0 (index 0), the two interpolants in between
        const idx = t < 1 / 6 ? 1 : t < 1 / 2 ? 3 : t < 5 / 6 ? 2 : 0;
        indices = (indices << 2) | idx;
    }

    out[outOff] = c0 & 0xff; out[outOff + 1] = (c0 >> 8) & 0xff;
    out[outOff + 2] = c1 & 0xff; out[outOff + 3] = (c1 >> 8) & 0xff;
    out[outOff + 4] = indices & 0xff;
    out[outOff + 5] = (indices >> 8) & 0xff;
    out[outOff + 6] = (indices >> 16) & 0xff;
    out[outOff + 7] = (indices >>> 24) & 0xff;
}

/** Compress a padded RGBA image to BC1. Dimensions must be multiples of 4. */
function compressDXT1(src, w, h) {
    const blocksX = w >> 2, blocksY = h >> 2;
    const out = new Uint8Array(blocksX * blocksY * 8);
    let off = 0;
    for (let by = 0; by < blocksY; by++) {
        for (let bx = 0; bx < blocksX; bx++) {
            encodeBlock(src, w, bx * 4, by * 4, out, off);
            off += 8;
        }
    }
    return out;
}

/**
 * Build the full compressed mip chain for one chunk texture.
 *
 * Two constraints drive the shape of this:
 *  - WebGL rejects an incomplete mip chain, so it must run all the way to 1×1.
 *    A texture with a partial chain and a mipmapped min filter renders black.
 *  - Every level's declared size must be exactly half the previous one. Padding is
 *    therefore applied once, to level 0; the chain is then built from the padded
 *    image, and only the 2×2 and 1×1 tails need block padding again — those are
 *    declared at their true size while still carrying one 8-byte block, which is
 *    how DDS chains encode them.
 *
 * @returns {{mips: Array<{width,height,data:Uint8Array}>, padWidth, padHeight}}
 */
function buildMipChain(rgba, width, height) {
    const flipped = flipY(rgba, width, height);
    const base = padTo4(flipped, width, height);

    const mips = [];
    let level = base.data;
    let lw = base.width, lh = base.height;

    while (true) {
        // Every level is padded to whole blocks before encoding, while its declared
        // size stays the exact halved size. The driver sizes the upload as
        // ceil(w/4) * ceil(h/4) * 8, so a level like 778 px wide needs 195 blocks,
        // not the 194 that fit inside it — supply 194 and the upload is rejected
        // with GL_INVALID_VALUE and the whole texture samples black.
        const p = padTo4(level, lw, lh);
        mips.push({
            width: lw,
            height: lh,
            data: compressDXT1(p.data, p.width, p.height)
        });

        if (lw === 1 && lh === 1) break;
        const next = downsample(level, lw, lh);
        level = next.data; lw = next.width; lh = next.height;
    }

    return { mips, padWidth: base.width, padHeight: base.height };
}

// Guarded so the encoder can also be required from a Node test harness
if (typeof self !== 'undefined' && typeof self.postMessage === 'function') {
    self.onmessage = function (e) {
        const { id, rgba, width, height } = e.data;
        try {
            const { mips, padWidth, padHeight } = buildMipChain(new Uint8Array(rgba), width, height);
            const transfer = mips.map(m => m.data.buffer);
            self.postMessage({ id, ok: true, mips, padWidth, padHeight, width, height }, transfer);
        } catch (err) {
            self.postMessage({ id, ok: false, error: err.message });
        }
    };
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { buildMipChain, compressDXT1, padTo4, downsample, flipY };
}
